config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  resources :users, except: [:index] do 
    get '/followers' => 'relationships#index_followers'
    get '/following' => 'relationships#index_following'
    resources :beards, except: [:index]
  end

  get '/kenny_login' => 'home#login'
  post '/kenny_login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :ratings, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :beards, except: [:index, :edit, :update]
  post '/follow' => 'relationships#follow'
  post '/unfollow' => 'relationships#unfollow'
  get '/sort_by_beard' => 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
end

app/models/beard.rb
class Beard < ApplicationRecord
  belongs_to :user

  has_many :ratings, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  validates :picture_url, :format => URI::regexp(%w(http https))

  def self.top_beards(type = nil)
    beard_ranks = {}
        beards = (type == nil) ? Beard.all : Beard.where(beard_type: type)
        beards.each do |beard|
            beard_ranks[beard]
            rating_sum = 0
            average_rating = 0
            beard.ratings.each do |r|
                rating_sum += r.value
            end

            if beard.ratings.length > 0
                average_rating = (rating_sum.to_f / (beard.ratings.length)).round(1)
            end
            beard_ranks[beard] = average_rating
        end

        sorted = beard_ranks.sort_by do |key, value| 
            value
        end.reverse.to_h

        sorted.keys.slice(0..9)
    
  end
  
end

app/controllers/beards_controller.rb
class BeardsController < ApplicationController
  def show
    @beard = Beard.find(params[:id])
    session[:beard_id] = @beard.id
    
    rating_sum = 0
    @beard.ratings.each do |r|
      rating_sum += r.value
    end
    
    if @beard.ratings.length > 0
      @average_rating = (rating_sum.to_f / (@beard.ratings.length)).round(1)
    end
  end

  def new
    @beard = Beard.new
  end

  def create
    new_beard = Beard.new(beard_params)
    new_beard.user_id = session[:user_id]
    if new_beard.save
      redirect_to new_beard
    else
      flash[:errors] = new_beard.errors.full_messages
      redirect_to new_beard_path
    end
  end

  # def edit
  #   @beard = Beard.find(params[:id])
  # end

  # def update
  #   @beard = Beard.find(params[:id])
  #   @beard.update(beard_params)
  #   redirect_to @beard
  # end

  def destroy
    Beard.find(params[:id]).destroy
    redirect_to user_path(session[:user_id])
  end

  private

  def beard_params
    params.require(:beard).permit(:beard_type, :picture_url)
  end
end

app/helpers/beards_helper.rb
module BeardsHelper
end

app/views/beards/edit.html.erb
<h1>Beards#edit</h1>
<p>Find me in app/views/beards/edit.html.erb</p>

app/views/beards/index.html.erb
<h1>Beards#index</h1>
<p>Find me in app/views/beards/index.html.erb</p>

app/views/beards/new.html.erb
<h1>Show Me Your Beard</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |message| %>
    <p><font color='crimson'><%= message %></font></p>
  <% end %>
<% end %>

<%= form_with model: @beard do |f| %>
    <p>Picture URL: <%= f.text_field :picture_url %></p>
    <p>Beard Type: <%= f.select :beard_type, [['Balbo', 'Balbo'], ['Chin Curtain', 'Chin Curtain'],
                    ['Chinstrap', 'Chinstrap'], ['Friendly Muttonchops', 'Friendly Muttonchops'], 
                    ['Full Beard', 'Full Beard'], ['Fu Manchu', 'Fu Manchu'], ['Goat Patch', 'Goat Patch'],
                    ['Goatee', 'Goatee'], ['Goatee and Moustache', 'Goatee and Moustache'],
                    ['Horseshoe Moustache', 'Horseshoe Moustache'], ['Muttonchops', 'Muttonchops'],
                    ['Neckbeard', 'Neckbeard'], ['Shenandoah', 'Shenandoah'],['Sidewhiskers', 'Sidewhiskers'],
                    ['Soul Patch', 'Soul Patch'], ['Stubble', 'Stubble'],['Van Dyke', 'Van Dyke'], ['Zappa', 'Zappa']] %></p>
    <%= f.submit %>
<% end %>

app/views/beards/show.html.erb
<div class="grid-container">
  <div class="grid-item1">
    <img width="100%" src="<%= @beard.picture_url %>" %>
  </div>

  <div class="grid-item2">

    <p><font color='crimson'><%= flash[:carrots] %></font></p>

    <h1>Beard Grower: <%= link_to @beard.user.user_name, user_path(@beard.user.id) %></h1>
    <h1>Beard Type: <%= @beard.beard_type %>
    <br>

    <% if @beard.ratings.length > 0 %>
      <h3>LOOK AT THIS BEARD! IT HAS A RATING OF <%= @average_rating %>!</h3>
    <% else %>
      <h3>LOOK AT THIS BEARD! NO ONE HAS RATED IT! WILL YOU BE THE FIRST?!</h3>
    <% end %>

    <% user_rating = Rating.all.find do |rating| %>
      <% rating.user_id == session[:user_id] && rating.beard_id == @beard.id %>
    <% end %>

    <% if session[:user_id] %>
      <% if user_rating %>
        <%= form_with model: user_rating do |f| %>
          <p>Change Your Rating <%= f.select :value, (1..10) %></p>
          <p><%= f.submit "Change Rating" %></p>
        <% end %>
      <% else %>
        <%= form_for Rating.new do |f| %>
          <p>Rating <%= f.select :value, (1..10) %></p>
          <p><%= f.submit "Rate this Beard" %></p>
        <% end %>
      <% end %>
    <% end %>

    <% if session[:user_id] %>
      <%= form_for Comment.new do |f| %>
        <p>Add a comment:</p>
        <%= f.text_area :commentary %>
        <p><%= f.submit "Post Comment" %>
      <% end %>
    <% end %>

    <% if session[:user_id] == nil %>
      <p>Ratings and comments are disable for non-users. 
      <%= link_to 'Log in', kenny_login_path %> or 
      <%= link_to 'sign up', new_user_path %> to begin rating and commenting on beards!</p>
    <% end %>

    <h3><u>COMMENTS</u></h3>

    <% @beard.comments.each do |c| %>
      <% if c.user.id == session[:user_id] %>
        <p>"<%= c.commentary %>" ~ <%= link_to c.user.user_name, user_path(c.user.id) %>
        
        <div>
          <div class="inline-button" display="inline-block">
            <%= form_tag edit_comment_path(c.id), method: "get" do %>
            <%= submit_tag "Edit Comment" %>
            <% end %>
          </div>
          <div class="inline-button" display="inline-block">
            <%= form_tag comment_path(c.id), method: "delete" do %>
            <%= submit_tag "Delete Comment" %>
            <% end %>
          </div>
        </div>
      <% else %>
        "<%= c.commentary %>" ~ <%= link_to c.user.user_name, user_path(c.user.id) %></p>
      <% end %>
    <% end %>

    <% if session[:user_id] == @beard.user.id %>
      <%= form_tag beard_path(@beard.id), method: "delete" do %>
        <%= submit_tag "Delete Your Beard :(" %>
      <% end %>
    <% end %>
  </div>
</div>