config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  resources :users, except: [:index] do 
    get '/followers' => 'relationships#index_followers'
    get '/following' => 'relationships#index_following'
    resources :beards, except: [:index]
  end

  get '/kenny_login' => 'home#login'
  post '/kenny_login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :ratings, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :beards, except: [:index, :edit, :update]
  post '/follow' => 'relationships#follow'
  post '/unfollow' => 'relationships#unfollow'
  get '/sort_by_beard' => 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    
    has_many :active_relationships, class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy

    has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent: :destroy

    has_many :following, through: :active_relationships, source: :followed, dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower, dependent: :destroy

    has_many :beards, dependent: :destroy
    has_many :ratings, through: :beards, dependent: :destroy
    has_many :comments, through: :beards, dependent: :destroy


    validates :user_name, length: {minimum: 2}
    validates :user_name, uniqueness: true
    validates :name, length: {minimum: 2}
    validates :age, numericality: {greater_than: 0}
    validates :profile_picture, presence: true
    validates :profile_picture, :format => URI::regexp(%w(http https))
    validates :password, length: {minimum: 5}


    def is_following?(id)
        follows = Relationship.where(follower_id: self.id,followed_id: id)
        do_i_follow = follows.length > 0 ? true : false
    end

    def follow_beards
        beards = {}
        self.following.each do |follow|
            follow.beards.each do |beard|
                beards[beard] = beard.created_at
            end
        end

        sorted_beards = beards.sort_by do |key, value| 
            value
        end.reverse.to_h

        sorted_beards.keys.slice(0..4)

    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login
  skip_before_action :require_login, only: [:new, :create, :show]

  def show
    @user = User.find(params[:id])

    if session[:user_id]
      @login = User.find(session[:user_id])
      session[:followed_id] = params[:id]
      @is_following = @login.is_following?(params[:id]) ? true : false
    end

  end

  def new
    @user = User.new
  end

  def create
    new_user = User.new(user_params)

    if new_user.valid?
      new_user.save
      redirect_to kenny_login_path
    else
      flash[:errors] = new_user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    update_user = User.find(params[:id])

    if update_user.update(user_params)
      redirect_to update_user
    else
      flash[:errors] = update_user.errors.full_messages
      redirect_to edit_user_path
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :name, :age, :bio,:instagram, :twitter, :profile_picture, :password, :password_confirmation)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <p><font color='red'><%= message %></font></p>
  <% end %>
<% end %>

<%= form_with model: @user do |f|%>
    <p>User Name: <%= f.text_field :user_name %></p>
    <p>Name: <%= f.text_field :name %></p>
    <p>Age: <%= f.number_field :age %></p>
    <p>Bio: <%= f.text_area :bio %></p>
    <p>Instagram: <%= f.text_field :instagram %></p>
    <p>Twitter: <%= f.text_field :twitter %></p>
    <p>Profile Picture URL: <%= f.text_field :profile_picture %></p>
    <p>Password: <%= f.password_field :password %></p>
    <p>Confirm Password: <%= f.password_field :password_confirmation %></p>
    <p><%= f.submit %></p>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <p><font color='red'><%= message %></font></p>
  <% end %>
<% end %>

<%= form_with model: @user do |f|%>
    <p>User Name: <%= f.text_field :user_name %></p>
    <p>Name: <%= f.text_field :name %></p>
    <p>Age: <%= f.number_field :age %></p>
    <p>Bio: <%= f.text_area :bio %></p>
    <p>Instagram: <%= f.text_field :instagram %></p>
    <p>Twitter: <%= f.text_field :twitter %></p>
    <p>Profile Picture URL: <%= f.text_field :profile_picture %></p>
    <p>Password: <%= f.password_field :password %></p>
    <p>Confirm Password: <%= f.password_field :password_confirmation %></p>
    <p><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<div class="grid-container">

    <div class="grid-item1">
        <img width="100%" src="<%= @user.profile_picture %>">
    </div>

    <div class="grid-item2">
        <% if session[:user_id] == @user.id%>
            <%= link_to 'Add Beard', new_beard_path %>
            |
            <%= link_to 'Edit Profile', edit_user_path %>
        <% end %>

    <h1>Username: <%= @user.user_name %></h1>

    <% if session[:user_id] %>
        <% if @user.id != session[:user_id]%>
            <% if @is_following %>
                <%=form_with url: :unfollow, method: :post do |f|%>
                    <%= f.submit 'Unfollow' %>
                <% end%>
            <% else %>
                <%=form_with url: :follow, method: :post do |f|%>
                    <%= f.submit 'Follow' %>
                <% end%>
            <% end%>
        <% end %>
    <% end %>
    <a href="<%= user_followers_path(@user.id) %>">Followers:</a> <%= @user.followers.count %></h4>  | <a href="<%= user_following_path(@user.id) %>">Following: </a><%= @user.following.count %><br />

    <h2>Name: <%= @user.name %></h2>

    <h3>Age: <%= @user.age %></h3>

    <h3>Bio:</h3>
    <p><%= @user.bio %></p><br />

    <h3>Twitter: <a href="https://www.twitter.com/<%= @user.twitter %>" target="_blank"><%= @user.twitter %></a></h3>

    <h3>Instagram: <a href="https://www.instagram.com/<%= @user.instagram %>" target="_blank"><%= @user.instagram %></a></h3>

    <h2>My Beards: </h2><br>
        <% @user.beards.each do |beard|%>
                <a href="/beards/<%= beard.id  %>">
                    <img src="<%= beard.picture_url %>" id="thumbnail" >
                </a>
        <% end %>
    </div>
</div>