config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  resources :users, except: [:index] do 
    get '/followers' => 'relationships#index_followers'
    get '/following' => 'relationships#index_following'
    resources :beards, except: [:index]
  end

  get '/kenny_login' => 'home#login'
  post '/kenny_login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :ratings, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :beards, except: [:index, :edit, :update]
  post '/follow' => 'relationships#follow'
  post '/unfollow' => 'relationships#unfollow'
  get '/sort_by_beard' => 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @followed_beards = []
        if session[:user_id]
            user = User.find(session[:user_id])
            @followed_beards = user.follow_beards.last(5)
        end

        if params.has_key?(:beard_type)
            @beards = Beard.top_beards(params[:beard_type])
        else
            @beards = Beard.top_beards
        end

    end

    def login
        
    end

end

app/views/home/index.html.erb
<h2>Top Beards: </h2>
<%= form_with url: sort_by_beard_path, method: :get, local: true do |f|%>
    <%= f.select :beard_type, [['Balbo', 'Balbo'], ['Chin Curtain', 'Chin Curtain'],
                    ['Chinstrap', 'Chinstrap'], ['Friendly Muttonchops', 'Friendly Muttonchops'], 
                    ['Full Beard', 'Full Beard'], ['Fu Manchu', 'Fu Manchu'], ['Goat Patch', 'Goat Patch'],
                    ['Goatee', 'Goatee'], ['Goatee and Moustache', 'Goatee and Moustache'],
                    ['Horseshoe Moustache', 'Horseshoe Moustache'], ['Muttonchops', 'Muttonchops'],
                    ['Neckbeard', 'Neckbeard'], ['Shenandoah', 'Shenandoah'],['Sidewhiskers', 'Sidewhiskers'],
                    ['Soul Patch', 'Soul Patch'], ['Stubble', 'Stubble'],['Van Dyke', 'Van Dyke'], ['Zappa', 'Zappa']] %>
    <%= f.submit 'Go Home' %>
<% end %>
<% @beards.each do |beard|%>
    <a href="/beards/<%= beard.id %>"><img src="<%= beard.picture_url %>" id="bigthumb"></a>
<% end %>
<h2>Feed: </h2>
<% if @followed_beards.length > 0%>
    <% @followed_beards.each do |beard|%>
        <p><%= beard.user.user_name %> @ <%= beard.created_at %></p>
        <a href="/beards/<%= beard.id %>"><img src="<%= beard.picture_url %>" id="bigthumb"></a>
    <% end %>
<% end %>

app/views/home/login.html.erb
<div>
    <h1>It's a danger zone ahead. Better loggin first.</h1>
</div>

<%= form_with url: kenny_login_path, method: :post do |f|%>
    <p>Username: <%= f.text_field 'user_name' %></p>
    <p>Password: <%= f.password_field 'password' %></p>
    <%= f.submit 'Loggin'%>
<% end %>
<% if flash[:errors] %>
    <p><font color="crimson"><%= flash[:errors] %></font></p>
<% end %>

<body background="http://www.thexboxhub.com/wp-content/uploads/2016/11/kenny-loggins.jpg"></body>

app/views/home/sort_by_beard.html.erb
<% @beards.each do |beard|%>
    <a href="/beards/<%= beard.id %>"><img src="<%= beard.picture_url %>" id="bigthumb"></a>
<% end %>