config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  resources :users, except: [:index] do 
    get '/followers' => 'relationships#index_followers'
    get '/following' => 'relationships#index_following'
    resources :beards, except: [:index]
  end

  get '/kenny_login' => 'home#login'
  post '/kenny_login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :ratings, only: [:new, :create, :edit, :update, :destroy]
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :beards, except: [:index, :edit, :update]
  post '/follow' => 'relationships#follow'
  post '/unfollow' => 'relationships#unfollow'
  get '/sort_by_beard' => 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Rate My Beard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body bgcolor=grey>
    <table class="tableWithBackground" width="auto" height="350px">
    
    
    <img class="tableBackground" src="https://i.imgur.com/eVbpFMf.jpg">

    <tr>
      <td colspan="5"></td>
    </tr>

    <tr>
      <td colspan="5"></td>
      <td colspan="5" style="font-size: 4em; font-weight: bold; position: absolute; top: 75px;">
        <a href="/">RateMyBeard</a></td>
    </tr>
    <tr>
      <td width="100px" height="20px" halign="right" valign="center">
        <% if session[:user_id] %>
          <a href="/users/<%= session[:user_id] %>">My Profile</a>
        <% else %>
          <%= link_to 'Login', kenny_login_path %>
        <% end %>
      </td>
      <td width="100px" height="20px" halign="right" valign="center">
        <% if session[:user_id] %>
          <%= link_to 'Log Out', logout_path, method: 'post' %>
        <% else %>
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>
      </td>
      <td width="100px" height="20px" halign="right" valign="center">
        <% if session[:user_id] && RandomBeard.new(session[:user_id]).beard != nil%>
          <%= link_to 'Rate Beards', "/beards/#{RandomBeard.new(session[:user_id]).beard.id}" %>
        <% elsif session[:user_id] %>
          <% flash[:carrots] = "You've already rated all the beards!" %>
          <%= link_to 'Rate Beards', "/beards/#{Beard.all.sample.id}"%>
        <% end %>
      </td>
    </tr>

    
  </table>
    <%= yield %>
  </body>
</html>

app/views/layouts/application_2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rate My Beard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  

  <body bgcolor=grey>
    <table class="tableWithBackground" width="auto" height="350px">
    
    
    <img class="tableBackground" src="https://i.imgur.com/eVbpFMf.jpg">

    <tr>
      <td colspan="5"></td>
    </tr>

    <tr>
      <td colspan="5"></td>
      <td colspan="5" style="font-size: 4em; font-weight: bold; position: absolute; top: 75px;">
        <a href="/">RateMyBeard</a></td>
    </tr>
    <tr>
      <td width="100px" height="20px" halign="right" valign="center">
        <% if session[:user_id] %>
          <a href="/users/<%= session[:user_id] %>">My Profile</a>
        <% else %>
          <%= link_to 'Login', kenny_login_path %>
        <% end %>
      </td>
      <td width="100px" height="20px" halign="right" valign="center">
        <% if session[:user_id] %>
          <%= link_to 'Log Out', logout_path, method: 'post' %>
        <% else %>
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>
      </td>
      <td width="100px" height="20px" halign="right" valign="center">
        <% if session[:user_id] %>
          <%= link_to 'Rate Beards', "/beards/#{Beard.all.sample.id}" %>
        <% end %>
      </td>
    </tr>

    
  </table>
    <%= yield %>
  </body>
</html>